// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxyY4ZDMD7UbDoKy91KcmwU6_dwgd5F18',
    appId: '1:622836598942:web:bcb98699d6d3267c0e138f',
    messagingSenderId: '622836598942',
    projectId: 'skillhub-90854',
    authDomain: 'skillhub-90854.firebaseapp.com',
    storageBucket: 'skillhub-90854.firebasestorage.app',
    measurementId: 'G-YWTFHVJ56R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuYv6o9g-YiiE3BEmyY7DotYVN5ZWLzXE',
    appId: '1:622836598942:android:6360e519d6b997c60e138f',
    messagingSenderId: '622836598942',
    projectId: 'skillhub-90854',
    storageBucket: 'skillhub-90854.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACd6fdleA5oL58STkstvzBzyiXXUV7GPk',
    appId: '1:622836598942:ios:2f959777734a18010e138f',
    messagingSenderId: '622836598942',
    projectId: 'skillhub-90854',
    storageBucket: 'skillhub-90854.firebasestorage.app',
    iosBundleId: 'com.example.skillshareHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACd6fdleA5oL58STkstvzBzyiXXUV7GPk',
    appId: '1:622836598942:ios:2f959777734a18010e138f',
    messagingSenderId: '622836598942',
    projectId: 'skillhub-90854',
    storageBucket: 'skillhub-90854.firebasestorage.app',
    iosBundleId: 'com.example.skillshareHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxyY4ZDMD7UbDoKy91KcmwU6_dwgd5F18',
    appId: '1:622836598942:web:4a418299b436fcdd0e138f',
    messagingSenderId: '622836598942',
    projectId: 'skillhub-90854',
    authDomain: 'skillhub-90854.firebaseapp.com',
    storageBucket: 'skillhub-90854.firebasestorage.app',
    measurementId: 'G-00JD6ERPVR',
  );
}
